const CURRENT_MONTH_INCREASE = 'CURRENT_MONTH_INCREASE';
const CURRENT_MONTH_DECREASE = 'CURRENT_MONTH_DECREASE';

const NEW_RECORD_SUBMIT = 'NEW_RECORD_SUBMIT';
const DELETE_RECORD = 'DELETE_RECORD';
const EDIT_RECORD = 'EDIT_RECORD';
const V_MODEL_NEWRECORD_NAME = 'V_MODEL_NEWRECORD_NAME',
  V_MODEL_NEWRECORD_PRICE = 'V_MODEL_NEWRECORD_PRICE',
  V_MODEL_NEWRECORD_TYPE = 'V_MODEL_NEWRECORD_TYPE',
  V_MODEL_NEWRECORD_DATE = 'V_MODEL_NEWRECORD_DATE';
// const CURRENT_MONTH_DECREASE = 'CURRENT_MONTH_DECREASE';

export {
  CURRENT_MONTH_INCREASE,
  CURRENT_MONTH_DECREASE,
  NEW_RECORD_SUBMIT,
  DELETE_RECORD,
  EDIT_RECORD,

  V_MODEL_NEWRECORD_NAME,
  V_MODEL_NEWRECORD_PRICE,
  V_MODEL_NEWRECORD_TYPE,
  V_MODEL_NEWRECORD_DATE
}
